### ISSUE TITLE
Missing merged/closed pull-requests from report?

### ISSUE THREAD

**Issue by ThomasAdam** [heinrichreimer/action-github-changelog-generator#19]
### Describe the bug
I used to use `ferrarimarco/github-changelog-generator` via docker manually to produce a `CHANGELOG.md` file.  Since learning of your Github Actions command, I've switched to that, and noticed some discrepancies in the output.

This has lead to ferrarimarco/github-changelog-generator` docker image producing different results to `heinrichreimer/action-github-changelog-generator`.

### Reproduce
1.  In a repository of your choice (and assuming you can run `Docker`), run:

```
docker run -it --rm -v $(pwd):$(pwd) ferrarimarco/github-changelog-generator -t <github token> --user <github_user> --project <github_project> -o "$(pwd)/CHANGELOG.md"github_user
```
Where:

* `<github_token>` is a token allowing you to run commands against GitHub
* `<githug_user>` is a username of a GitHub account
* `<github_project>` is a project on Github.

### Expected behavior
In comparing the output from both runs, the invocation from `ferrarimarco/github-changelog-generator ` will show an inclusion of merged pull-requests, where using `heinrichreimer/action-github-changelog-generator` does not.

Here is the options from `ferrarimarco/github-changelog-generator`:

```
Using these options:                                                                                                                                                                                    
:date_format=>"%Y-%m-%d"                                                                                                                                                                                
:output=>"/home/n6tadam/projects/fvwm/fvwm3/CHANGELOG.md"                                                                                                                                               
:base=>"HISTORY.md"                                                                                                                                                                                     
:issues=>true                                                                                                                                                                                           
:add_issues_wo_labels=>true                                                                                                                                                                             
:add_pr_wo_labels=>true                                                                                                                                                                                 
:pulls=>true                                                                                                                                                                                            
:filter_issues_by_milestone=>true                                                                                                                                                                       
:author=>true                                                                                                                                                                                           
:unreleased=>true                                                                                                                                                                                       
:unreleased_label=>"Unreleased"                                                                                                                                                                         
:compare_link=>true                                                                                                                                                                                     
:exclude_labels=>["duplicate", "question", "invalid", "wontfix", "Duplicate", "Question", "Invalid", "Wontfix", "Meta: Exclude From Changelog"]                                                         
:summary_labels=>["Release summary", "release-summary", "Summary", "summary"]                                                                                                                           
:breaking_labels=>["backwards-incompatible", "Backwards incompatible", "breaking"]                                                                                                                      
:enhancement_labels=>["enhancement", "Enhancement", "Type: Enhancement"]                                                                                                                                
:bug_labels=>["bug", "Bug", "Type: Bug"]                                                                                                                                                                
:deprecated_labels=>["deprecated", "Deprecated", "Type: Deprecated"]                                                                                                                                    
:removed_labels=>["removed", "Removed", "Type: Removed"]                                                                                                                                                
:security_labels=>["security", "Security", "Type: Security"]                                                                                                                                            
:configure_sections=>{}                                                                                                                                                                                 
:add_sections=>{}                                                                                                                                                                                       
:issue_line_labels=>[]                                                                                                                                                                                  
:max_issues=>nil                                                                                                                                                                                        
:simple_list=>false                                                                                                                                                                                     
:ssl_ca_file=>nil                                                                                                                                                                                       
:verbose=>true                                                                                                                                                                                          
:header=>"# Changelog"                                                                                                                                                                                  
:merge_prefix=>"**Merged pull requests:**"                                                                                                                                                              
:issue_prefix=>"**Closed issues:**"                                                                                                                                                                     
:summary_prefix=>""                                                                                                                                                                                     
:breaking_prefix=>"**Breaking changes:**"                                                                                                                                                               
:enhancement_prefix=>"**Implemented enhancements:**"                                                                                                                                                    
:bug_prefix=>"**Fixed bugs:**"                                                                                                                                                                          
:deprecated_prefix=>"**Deprecated:**"                                                                                                                                                                   
:removed_prefix=>"**Removed:**"                                                                                                                                                                         
:security_prefix=>"**Security fixes:**"                                                                                                                                                                 
:http_cache=>true                                                                                                                                                                                       
:require=>[]                                                                                                                                                                                            
:token=>"hidden value" 
:user=>"fvwmorg"
:project=>"fvwm3"
```

This output seems to be the same when running via `heinrichreimer/action-github-changelog-generator`, and hence in the Github Actions YAML file:

```
  changelog:                                                                                                                                                                                            
      name: Update Changelog                                                                                                                                                                            
      runs-on: ubuntu-20.04                                                                                                                                                                             
      needs: build                                                                                                                                                                                      
      steps:                                                                                                                                                                                            
          - name: Checkout code                                                                                                                                                                         
            if: github.ref == 'refs/heads/master'                                                                                                                                                       
            uses: actions/checkout@v2                                                                                                                                                                   
            with:                                                                                                                                                                                       
                ref: master                                                                                                                                                                             
          - name: Update CHANGELOG                                                                                                                                                                      
            if: github.ref == 'refs/heads/master'
            uses: heinrichreimer/github-changelog-generator-action@v2.1.1
            with:
                token: ${{ secrets.GITHUB_TOKEN }} 
                issues: true
                issuesWoLabels: false
                pullRequests: true
                prWoLabels: true
                author: true
                unreleased: true
                stripGeneratorNotice: true
                verbose: true
                compareLink: true
                httpCache: true
                filterByMilestone: true
          - name: Commit CHANGELOG
            if: github.ref == 'refs/heads/master'
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_user_name: Fvwm Automation
                commit_user_email: fvwm-automation@example.org
                commit_author: Fvwm Automation <fvwm-automation@example.org>
                commit_message: '[AUTO]: update CHANGELOG'
                file_pattern: CHANGELOG.md
```

Yet, despite the above working, there is still a clear difference in that `heinrichreimer/action-github-changelog-generator` is not including the same information as running the Docker command mentioned earlier.

Thanks!
