### ISSUE TITLE
[Question] Usage example seems to be incomplete.

### ISSUE THREAD

**Issue by MikeVaz** [heinrichreimer/action-github-changelog-generator#26]
What you have

```yml
uses: heinrichreimer/github-changelog-generator-action@v2.1.1
with:
  token: ${{ secrets.GITHUB_TOKEN }}
```

Expected something like this

```yml
name: Changelog

on:
  pull_request:
    types: [closed]

  release:
    types: [published]

  issues:
    types: [closed, edited]

jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Generate change log
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
 ```
 
 If you provide a full example of the workflow it would help developers to adopt this action.
