### ISSUE TITLE
How to use the output?

### ISSUE THREAD

**Issue by Ismoh** [heinrichreimer/action-github-changelog-generator#40]
I use the example workflow.yml and realised that the output is put somewhere, but I would like to use it to create a CHANGELOG.md.
CHANGELOG.md was created in `Generated log placed in /github/workspace/CHANGELOG.md`, but how can I access it?
Can someone give me a hint how to do so?

This is my changelog-generator.yml:
https://github.com/Ismoh/NoitaMP/blob/72-include-changelog-generator/.github/workflows/changelog-generator.yml
And the workflow run:
https://github.com/Ismoh/NoitaMP/actions/runs/3118913727/jobs/5058526684

In addition to this I thought the release body content would be updated with the generated changelog output.

Edit: Found the path here: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#file-systems

What am I doing wrong?

**Comment by Ismoh** [comment]
If there is anyone out there, having the same understanding issue in first glance, have a look on this:
```yaml
- name: Generate CHANGELOG.md
  id: generate_changelog <---- Add an id to the step
  uses: heinrichreimer/github-changelog-generator-action@v2.3
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    dateFormat: "%d.%m.%Y"
    output: "CHANGELOG.md"
    issueLineLabels: "ALL"
    breakingLabels: "backwards-incompatible,breaking,rework,refactor"
    futureRelease: $NEXT_VERSION

- name: Commit and push CHANGELOG.md, when merged
  env:
    CHANGELOG: ${{ steps.generate_changelog.outputs.changelog }} <--- use the output as shown here. 'generate_changelog' is the id in the previews step.
```
Hope this might help someone!
