### ISSUE TITLE
Question: issue with section

### ISSUE THREAD

**Issue by TGTGamer** [heinrichreimer/action-github-changelog-generator#6]
Heya, 

Hopefully nice easy one for you - having an issue with the section generation, not sure what I'm doing wrong.

The job step (the jobs really long but can be found [here](https://github.com/Videndum/Universal-GitAction-Workflows/blob/0fdab96002a76075783e46b41987f6d59a65f532/.github/workflows/pull-complete.yml#L81))
```yml
      - uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        if: ${{env.changelog}} == true
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pullRequests: ${{env.pullRequests}}
          prWoLabels: "${{env.prWoLabels}}"
          excludeLabels: "${{env.excludeLabels}}"
          breakingLabels: "${{env.breakingLabels}}"
          enhancementLabels: "${{env.enhancementLabels}}"
          bugLabels: "${{env.bugLabels}}"
          deprecatedLabels: "${{env.deprecatedLabels}}"
          removedLabels: "${{env.removedLabels}}"
          securityLabels: "${{env.securityLabels}}"
          stripGeneratorNotice: ${{env.stripGeneratorNotice}}
```

My env variables (Imported at start of job)
```yml
# Automatic Changelog
changelog: true # enable / disable
changelogRef: "master"
changelogFetchDepth: 0
pullRequests: true
prWoLabels: "skip-changelog"
breakingLabels: "Versioning - BREAKING"
enhancementLabels: "Type - Enhancement, Type - Feature"
bugLabels: "Type - Fix, Bug - Fixed"
deprecatedLabels: "Type - Decrecated"
removedLabels: "Type - Removal"
securityLabels: "security fix"
excludeLabels: "skip-changelog"
stripGeneratorNotice: "true"
```

my CHANGELOG.md
```md
# Changelog

## [v0.1.0](https://github.com/Videndum/Universal-GitAction-Workflows/tree/v0.1.0) (2020-07-21)

**Closed issues:**

- revert: 1613ffe4f4d721ae513bd56bc896a1013e3f2387 [\#41](https://github.com/Videndum/Universal-GitAction-Workflows/issues/41)
- bug: testing the labeler works [\#32](https://github.com/Videndum/Universal-GitAction-Workflows/issues/32)
- Feat: Test [\#8](https://github.com/Videndum/Universal-GitAction-Workflows/issues/8)
- label gen [\#2](https://github.com/Videndum/Universal-GitAction-Workflows/issues/2)

**Merged pull requests:**

- feat: profanity check [\#76](https://github.com/Videndum/Universal-GitAction-Workflows/pull/76)
- feat: publish release [\#75](https://github.com/Videndum/Universal-GitAction-Workflows/pull/75)
- feat: pull approval [\#74](https://github.com/Videndum/Universal-GitAction-Workflows/pull/74)
- revert: table of contents [\#68](https://github.com/Videndum/Universal-GitAction-Workflows/pull/68)
- docs: update contribution guidelines [\#64](https://github.com/Videndum/Universal-GitAction-Workflows/pull/64)
- fix: release [\#59](https://github.com/Videndum/Universal-GitAction-Workflows/pull/59)
- fix: remove triggers & solve \(Line: 71, Col: 13\) [\#56](https://github.com/Videndum/Universal-GitAction-Workflows/pull/56)
- fix: minor issues with workflow [\#55](https://github.com/Videndum/Universal-GitAction-Workflows/pull/55)
- fix: change token to ACCESS\_TOKEN [\#54](https://github.com/Videndum/Universal-GitAction-Workflows/pull/54)
- fix: triggers [\#52](https://github.com/Videndum/Universal-GitAction-Workflows/pull/52)
- fix: gpg values [\#50](https://github.com/Videndum/Universal-GitAction-Workflows/pull/50)
- fix: Copy & Rename step "commit" [\#47](https://github.com/Videndum/Universal-GitAction-Workflows/pull/47)
- feat: branch deletion without change [\#44](https://github.com/Videndum/Universal-GitAction-Workflows/pull/44)
- feat: automatic branch creation [\#43](https://github.com/Videndum/Universal-GitAction-Workflows/pull/43)
- feat: add automerge [\#38](https://github.com/Videndum/Universal-GitAction-Workflows/pull/38)
```
