### ISSUE TITLE
output only contains first line

### ISSUE THREAD

**Issue by sebhoss** [heinrichreimer/action-github-changelog-generator#7]
### Describe the bug
The step output only contains the first line of the generated changelog.

### Reproduce
1. Use `heinrichreimer/github-changelog-generator-action@v2.1.1`
2. Reference generated output in downstream step `${{ steps.generate-changelog.outputs.changelog }}`
3. Log changelog and see that step output does not contain the entire changelog

### Expected behavior
The step output should contain the entire changelog

**Comment by sebhoss** [comment]
My current work around is to use `juliangruber/read-file-action@v1` to read the generated changelog **file** like this:

```
- name: Read Changelog
  id: changelog
  uses: juliangruber/read-file-action@v1
  with:
    path: ./CHANGELOG.md
```

and then use `${{ steps.changelog.outputs.content }}` to use the generated changelog in other steps.
